runtime: nodejs
env: flex

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "22"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

beta_settings:
  cloud_sql_instances: sylvan-byway-428202-t3:southamerica-west1:mysql80projectmds
